# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: Maven@3
  #inputs:
   # mavenPomFile: 'pom.xml'
   # mavenOptions: '-Xmx3072m'
   # javaHomeOption: 'JDKVersion'
    #jdkVersionOption: '1.8'
   # jdkArchitectureOption: 'x64'
   # publishJUnitResults: true
    #testResultsFiles: '**/surefire-reports/TEST-*.xml'
    #goals: 'package'
    
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
    - run: chrome --version
     
    - name: Build with Maven
      run: mvn -B package --file pom.xml
